# -*- coding: utf-8 -*-
"""국민건강보험공단 데이터분포 파악.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPQtsiV_dUnZb_DaI0EcZKxRHenmS9Gf
"""

import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt

# euc-kr: 한글 2350자 표현 / cp949: 11172자 표현

df = pd.read_csv("국민건강보험공단_건강검진정보.CSV", encoding="cp949")

df.head()

df.info()

import os

# Mac OS의 경우와 그 외 OS의 경우로 나누어 설정

if os.name == 'posix':
    plt.rc("font", family="AppleGothic")

else:
    plt.rc("font", family="Malgun Gothic")

#. Null이란 값이 없음을 의미하는데 이는 데이터 분석 결과에 왜곡을 줄 수 있기에 적절한 처리가 필요합니다.

# 각 열마다 Null의 갯수를 모두 합쳐서 그래프를 그려줌

df.isnull().sum().plot.barh(figsize=(10,9))

h = df.hist(figsize=(30,20))

# iloc[ ] 함수를 이용하여 0이상 16번째 미만의 열의 데이터만 hist( )로 출력

h = df.iloc[:,:16].hist(figsize=(20,12))

# iloc[ ] 함수를 이용하여 16번째 열 이상의 데이터만 hist( )로 출력

h = df.iloc[:,16:].hist(figsize=(20,12), bins=100)

